default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root  # Replace with your PostgreSQL username
  password: V3lvetrevolver.  # Replace with your PostgreSQL password
  host: localhost

development:
  <<: *default
  database: wallet_transaction_system_development

test:
  <<: *default
  database: wallet_transaction_system_test

production:
  <<: *default
  database: wallet_transaction_system_production
  username: root  # Replace with production username if different
  password: <%= ENV['WALLET_TRANSACTION_SYSTEM_DATABASE_PASSWORD'] %>  # Secure your password with an environment variable